apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.image.repository }}
  type: {{ .Values.service.type }}