apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: vahiwe/techtrends:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        ports:
        - containerPort: 3111
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe: 
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 15
          periodSeconds: 60